// START OF JMUSICBOT CONFIG //
meta {
  configVersion = 1
}

discord {
  // Bot token (MUST be a bot token)
  token = ""

  // Owner user ID (17-18 digits)
  owner = 0
}

commands {
  // Primary prefix. If empty, you may support mention-prefix mode.
  prefix = "@mention"

  // Optional secondary prefix. "NONE" disables.
  altPrefix = "NONE"

  // Help command keyword
  help = "help"

  aliases {
    settings = [ "status" ]

    lyrics = []
    nowplaying = [ "np", "current" ]
    play = []
    playlists = [ "pls" ]
    queue = [ "list" ]
    remove = [ "delete" ]
    scsearch = []
    search = [ "ytsearch" ]
    shuffle = []
    skip = [ "voteskip" ]

    prefix = [ "setprefix" ]
    setdj = []
    setskip = [ "setskippercent", "skippercent", "setskipratio" ]
    settc = []
    setvc = []

    forceremove = [ "forcedelete", "modremove", "moddelete", "modelete" ]
    forceskip = [ "modskip" ]
    movetrack = [ "move" ]
    pause = []
    playnext = []
    queuetype = []
    repeat = []
    skipto = [ "jumpto" ]
    stop = [ "leave" ]
    volume = [ "vol" ]
  }
}

presence {
  // "DEFAULT", "NONE", or custom string
  game = "DEFAULT"

  // ONLINE | IDLE | DND | INVISIBLE
  status = "ONLINE"

  // Show current song title in presence (works reliably for one guild only)
  songInStatus = false
}

ui {
  emojis {
    success = "🎶"
    warning = "💡"
    error = "🚫"
    loading = "⌚"
    searching = "🔎"
  }
}

nowPlaying {
  images = false
}

voice {
  stayInChannel = false
  aloneTimeUntilStopSeconds = 0
}

playback {
  maxTrackSeconds = 0
  maxYouTubePlaylistPages = 10
  skipRatio = 0.55

  youtube {
    useOAuth = false
  }

  // Explicit booleans are best for future additions/removals
  audioSources {
    youtube = true
    soundcloud = true
    bandcamp = true
    vimeo = true
    twitch = true
    beam = true
    getyarn = true
    nico = true
    http = true
    local = true
  }

  transforms = {}
}

paths {
  playlistsFolder = "Playlists"
}

updates {
  alerts = true
}

lyrics {
  default = "A-Z Lyrics"
}

logging {
  level = "info" // off,error,warn,info,debug,trace,all
}

dangerous {
  eval = false
  evalEngine = "Nashorn"
}
// END OF JMUSICBOT CONFIG //
